export const JOBS = [
  "Software Engineer",
  "Product Manager",
  "Designer",
  "Teacher",
  "Doctor",
  "Nurse",
  "Accountant",
  "Lawyer",
  "Engineer",
  "Architect",
  "Scientist",
  "Pharmacist",
  "Dentist",
  "Chef",
  "Artist",
  "Writer",
  "Photographer",
  "Musician",
  "Pilot",
  "Flight Attendant",
  "Police Officer",
  "Firefighter",
  "Mechanic",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Salesperson",
  "Marketing Specialist",
  "Business Analyst",
  "Consultant",
  "HR Manager",
  "Recruiter",
  "Data Scientist",
  "Data Analyst",
  "Financial Analyst",
  "Banker",
  "Real Estate Agent",
  "Entrepreneur",
  "Student",
  "Researcher",
  "Veterinarian",
  "Translator",
  "Interpreter",
  "Social Worker",
  "Psychologist",
  "Therapist",
  "Coach",
  "Trainer",
  "Athlete",
  "Farmer",
  "Fisherman",
  "Driver",
  "Waiter",
  "Bartender",
  "Receptionist",
  "Secretary",
  "Librarian",
  "Courier",
  "Security Guard",
  "Cleaner",
  "Other",
];
